version: '3.7'
name: banklyco
services:
  mic-users:
    image: mic-users
    build: mic-users/
    ports:
      - "9090:9090"
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0.30
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=bankly_co
      - MAX_CONNECTION_TIME=240
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 5s
      timeout: 5s
      retries: 20
      
networks:
  default:
    name: banklyco
