version: '3.7'
name: BANCKLY.CO
services: 
  mic-users:
    image: mic-users
    container_name: mic-users-container
    build: mic-users/
    ports:
      - "9090:9090"
    depends_on:
      sonarqube:
        condition: service_started
      mysqldb:
        condition: service_healthy
      
  mic-walllet:
    image: mic-walllet
    container_name: mic-walllet-container
    build: wallet/
    ports:
      - "9091:9091"
    depends_on:
      - mic-users
      - mongodb

  mic-operations:
    image: mic-operations
    container_name: mic-operations-container
    build: operations/
    ports:
      - "9092:9092"
    depends_on:
      - mic-walllet
      - postgresdb
    
  mysqldb:
    image: mysql:8.0.30
    container_name: mysql-container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=bankly_co
    ports:
      - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass" ]
      interval: 5s
      timeout: 5s
      retries: 20

  mongodb:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin

  postgresdb:
    image: postgres:latest
    hostname: postgresql
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=bankly_co
  
  sonarqube:
    image: sonarqube
    container_name: sonarqube-container
    ports:
      - 9000:9000
   
networks:
  default:
    name: net.bankly.co
