version: "3.7"
services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=bankly_co

networks:
  default:
    name: postgres_network